# Generated by Django 5.2 on 2025-04-12 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('category', models.CharField(choices=[('food', 'Food'), ('drink', 'Drink'), ('dessert', 'Dessert')], default='food', max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='menu_images/')),
            ],
        ),
    ]
