# Generated by Django 5.2 on 2025-04-12 16:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canapp', '0002_remove_menuitem_category_alter_menuitem_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
