# Generated by Django 5.2 on 2025-04-14 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canapp', '0004_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canapp.bill')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='canapp.menuitem')),
            ],
        ),
        migrations.AddField(
            model_name='bill',
            name='items',
            field=models.ManyToManyField(through='canapp.BillItem', to='canapp.menuitem'),
        ),
    ]
